bottler-web/src/main/java/cz/muni/fi/pa165/bottler/web/StampsActionBean.java
package cz.muni.fi.pa165.bottler.web;

import cz.muni.fi.pa165.bottler.data.dto.StampDto;
import cz.muni.fi.pa165.bottler.service.StampService;
import java.util.List;
import net.sourceforge.stripes.action.Before;
import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.ErrorResolution;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.LocalizableMessage;
import net.sourceforge.stripes.action.RedirectResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.action.UrlBinding;
import net.sourceforge.stripes.controller.LifecycleStage;
import net.sourceforge.stripes.integration.spring.SpringBean;
import net.sourceforge.stripes.validation.LocalizableError;
import net.sourceforge.stripes.validation.Validate;
import net.sourceforge.stripes.validation.ValidateNestedProperties;
import net.sourceforge.stripes.validation.ValidationErrorHandler;
import net.sourceforge.stripes.validation.ValidationErrors;
import org.apache.shiro.SecurityUtils;
import org.apache.shiro.subject.Subject;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

/**
 * Action bean for stamps
 *
 * @author Vit Stanislav <373843@mail.muni.cz>
 */
@UrlBinding("/stamps/{$event}/{stamp.id}")
public class StampsActionBean extends BaseActionBean implements ValidationErrorHandler {

    @SpringBean
    protected StampService stampService;
    private DateTimeFormatter fmt;
    // list for stamps
    private List<StampDto> stamps;

    private boolean userIsPermittedToEdit;

    private boolean userIsPermittedToDelete;

    private boolean userIsPermittedToCreate;

    public boolean isUserIsPermittedToEdit() {
        return userIsPermittedToEdit;
    }

    public boolean isUserIsPermittedToDelete() {
        return userIsPermittedToDelete;
    }

    public boolean isUserIsPermittedToCreate() {
        return userIsPermittedToCreate;
    }

    public List<StampDto> getTests() {
        return stamps;
    }
    // one stamp
    @ValidateNestedProperties(value = {
        @Validate(on = {"create", "update"}, field = "numberOfStamp", required = true),
        @Validate(on = {"create", "update"}, field = "issuedDate",
                required = true, converter = JodaDateTimeConverter.class)
    })
    private StampDto stamp;

    public void setStamp(StampDto stamp) {
        this.stamp = stamp;
    }

    public StampDto getStamp() {
        return this.stamp;
    }

    // listing all
    @DefaultHandler
    public Resolution list() {
        fmt = DateTimeFormat.forPattern("yyyy-MM-dd HH:mm:ss");
        stamps = stampService.getAllStamps();
        return new ForwardResolution("/stamps.jsp");
    }

    public Resolution create() {
        try {
            stampService.createStamp(stamp);
            getContext().getMessages().add(new LocalizableMessage("stamp.was_created"));
            return new RedirectResolution(this.getClass(), "list");
        } catch (Exception e) {
            getContext().getMessages().add(new LocalizableError("stamp.wasnt_created"));
            System.err.printf("here::::" + e.getMessage());
            return new RedirectResolution(this.getClass(), "list");
        }
    }

    public Resolution edit() {
        return new ForwardResolution("/stampEdit.jsp");

    }

    public Resolution delete() {
        try {
            stamp = stampService.findStampById(stamp.getId());
            stampService.removeStamp(stamp);
            getContext().getMessages().add(new LocalizableMessage("stamp.was_deleted"));
        } catch (Exception e) {
            getContext().getMessages().add(new LocalizableMessage("stamp.wasnt_deleted"));
        }
        return new RedirectResolution(this.getClass(), "list");
    }

    public Resolution update() {

        try {
            stampService.updateStamp(stamp);
            getContext().getMessages().add(new LocalizableMessage("stamp.was_saved"));
            return new RedirectResolution(this.getClass(), "list");
        } catch (Exception e) {
            getContext().getValidationErrors().addGlobalError(new LocalizableError("stamp.wasnt_saved"));
            return new ForwardResolution(this.getClass(), "edit");
        }


    }

    public Resolution detail() {

        return new ForwardResolution("/stampDetail.jsp");
    }

    @Override
    public Resolution handleValidationErrors(ValidationErrors ve) throws Exception {
        stamps = stampService.getAllStamps();
        return null;
    }

    /**
     * Loads stamp from DB before edit and update call
     *
     * @return
     */
    @Before(stages = LifecycleStage.BindingAndValidation, on = {"edit", "update", "detail"})
    public Resolution loadStampFromDatabase() {
        String ids = getContext().getRequest().getParameter("stamp.id");
        if (ids == null) {
            return new ErrorResolution(400, "ID not specified.");
        }

        stamp = stampService.findStampById(Long.parseLong(ids));

        if (stamp == null) {
            return new ErrorResolution(404, "Stamp with this ID not found.");
        }

        return null;
    }

    @Before(stages = LifecycleStage.BindingAndValidation, on = {"list"})
    public Resolution loadCurrentUser() {
        Subject currentUser = SecurityUtils.getSubject();
        userIsPermittedToCreate = currentUser.hasRole("admin");
        userIsPermittedToEdit = currentUser.hasRole("admin");
        userIsPermittedToDelete = currentUser.hasRole("admin");
        return null;
    }
}

bottler-web/src/main/webapp/blocks/bottleEditForm.jsp
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>

<s:form beanclass="cz.muni.fi.pa165.bottler.web.BottlesActionBean" class="center-block" id="bottlesActionBean">

    <h4><f:message key="bottle.edit"/></h4>
    <br />
    <s:hidden name="bottle.id" />
    <%@include file="bottleForm.jsp"%>
    <div class="pull-right">
        <s:link class="btn btn-default" href="/bottlers"><f:message key="cancel"/></s:link>
        <s:submit name="update" class="btn btn-primary"><f:message key="bottle.save"/></s:submit>
    </div>

</s:form>

bottler-web/src/main/webapp/blocks/bottleForm.jsp
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib prefix="f" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="joda" uri="http://www.joda.org/joda/time/tags" %>

<s:useActionBean beanclass="cz.muni.fi.pa165.bottler.web.BottlesActionBean" var="bottlesActionBean"/>
<div class="form-group">
    <label for="bottle-liquor-input"><f:message key="bottle.liquor"/></label>
    <s:select name="bottle.liquor" class="form-control" id="bottle-liquor-input">
        <s:options-collection collection="${bottlesActionBean.liquors}" value="id" label="name"/>
    </s:select>
</div>

<div class="form-group">
    <label for="bottle-stamp-input"><f:message key="bottle.stamp"/></label>
    <s:select name="bottle.stamp" class="form-control" id="bottle-stamp-input">
        <s:options-collection collection="${bottlesActionBean.stamps}" value="id" label="numberOfStamp"/>
    </s:select>
</div>

<div class="form-group">
    <label for="bottle-producedDate-input"><f:message key="bottle.producedDate"/></label>
    <div class="form-group">
        <div class='input-group date' id='datetimepicker'>

            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
            </span>
            <%-- !! HACK !! - <s:text> doesn't accept data-format parameter --%>
            <joda:format value="${bottlesActionBean.bottle.producedDate}" var="bottleProdDate" pattern="yyyy-MM-dd HH:mm:ss" />
            <input data-format="YYYY-MM-DD HH:mm:ss" type="text" value="${bottleProdDate}" class="hidden"></input>
            <script>
                $(document).ready(function()
                {
                    $("#bottle-producedDate-input").val("${bottleProdDate}");
                });
            </script>
            <s:text name="bottle.producedDate" class="form-control" id="bottle-producedDate-input" />
            <%-- !! HACK  END !! --%>
        </div>
    </div>
</div>


<div class="form-group">
    <label for="bottle-lotCode-input"><f:message key="bottle.lotCode"/></label>
    <s:text name="bottle.lotCode" class="form-control" id="bottle-lotCode-input" />
</div>

<div class="form-group">
    <label for="bottle-store-input"><f:message key="bottle.store"/></label>
    <s:select name="bottle.store" class="form-control" id="bottle-store-input">
        <s:options-collection collection="${bottlesActionBean.stores}" value="id" label="name"/>
    </s:select>
</div>

<div class="form-group">
    <label for="bottle-sold"><f:message key="bottle.sold"/></label>
    <s:checkbox name="bottle.sold" class="form-control" id="bottle-sold" />
</div>

<script type="text/javascript">
    $(function() {
        $('#datetimepicker').datetimepicker({
        });
    });
</script>

bottler-web/src/main/webapp/blocks/bottleTestResultCreateForm.jsp
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>

<%@ taglib prefix="f" uri="http://java.sun.com/jsp/jstl/fmt" %>



<!-- form start -->
<s:form beanclass="cz.muni.fi.pa165.bottler.web.TestResultsActionBean" id="testResultCreateForm">
    <s:hidden name="modal_form" value="true" />

    <div class="modal modal_form" id="createTestResultModal" tabindex="-1" role="dialog" aria-labelledby="createTestResultModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><f:message key="testresult.create"/></h4>
                </div>

                <div class="modal-body">

                    <s:errors/>




                    <s:useActionBean beanclass="cz.muni.fi.pa165.bottler.web.BottlesActionBean" var="bottlesActionBean"/>

                    <s:hidden name="testResult.bottle" value="${bottlesActionBean.bottle.id}" />

                    <div class="form-group">
                        <label for="testresult_time_input"><f:message key="testresult.time"/></label>

                        <div class='input-group date' id='datetimepicker1'>
                            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                            </span>

                            <%-- !! HACK !! - <s:text> doesn't accept data-format parameter --%>
                            <input data-format="YYYY-MM-DD HH:mm:ss" type="text" class="hidden"></input>

                            <s:text name="testResult.time" class="form-control" id="testresult_time_input" />

                        </div>
                    </div>

                    <div class="form-group">
                        <label for="testresult_toxic_input"><f:message key="testresult.toxic"/></label>
                        <s:checkbox name="testResult.toxic" class="form-control" id="testresult_toxic_input" />
                    </div>

                    <script type="text/javascript">
                        $(function() {
                            $('#datetimepicker1').datetimepicker({
                            });
                            var dateInput = $('#datetimepicker1 input.form-control');
                            var dateString = dateInput.val();
                            dateString = dateString.replace('T', ' ').substr(0, 19);
                            dateInput.val(dateString);
                        });
                    </script>

                    <!-- <button type="submit" class="btn btn-default">Create testresult</button>-->


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><f:message key="cancel"/></button>

                  
                    <s:submit name="create" class="btn btn-primary"><f:message key="testresult.create"/></s:submit>
                </div>





            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->


</s:form>

bottler-web/src/main/webapp/blocks/liquorEditForm.jsp
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<!-- form start -->
<s:form beanclass="cz.muni.fi.pa165.bottler.web.LiquorsActionBean" class="center-block" id="liquorActionBean">

    <h4><f:message key="liquor.edit"/></h4>
    <br />
    <s:hidden name="liquor.id" />
    <%@include file="liquorForm.jsp"%>
    <div class="pull-right">
        <s:link class="btn btn-default" href="/liquors"><f:message key="cancel"/></s:link>
        <s:submit name="update" class="btn btn-primary"><f:message key="liquor.save"/></s:submit>
    </div>

</s:form>

bottler-web/src/main/webapp/blocks/producerCreateForm.jsp
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>


<!-- form start -->
<s:form beanclass="cz.muni.fi.pa165.bottler.web.ProducersActionBean" id="producerCreateForm">
    
    <s:hidden name="modal_form" value="true" />
    <div class="modal modal_form" id="createProducerModal" tabindex="-1" role="dialog" aria-labelledby="createProducerModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><f:message key="producer.create"/></h4>
                </div>

                <div class="modal-body">

                    <s:errors/>

                    <%@include file="producerForm.jsp"%>

                </div>
                <div class="modal-footer">

                    <button type="button" class="btn btn-default" data-dismiss="modal"><f:message key="cancel"/></button>

                    <s:submit name="create" class="btn btn-primary"><f:message key="producer.create"/></s:submit>
                    </div>




                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->


</s:form>


bottler-web/src/main/webapp/blocks/producerEditForm.jsp
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>


<!-- form start -->
<s:form beanclass="cz.muni.fi.pa165.bottler.web.ProducersActionBean" class="center-block" id="producerEditForm">


    <h4><f:message key="producer.edit"/></h4> 

<br />
    <s:hidden name="producer.id" />

    <%@include file="producerForm.jsp"%>

    <div class="pull-right">

    <s:link class="btn btn-default" href="/producers"><f:message key="cancel"/></s:link>

    <s:submit name="update" class="btn btn-primary"><f:message key="producer.save"/></s:submit>

</div>

</s:form>

bottler-web/src/main/webapp/blocks/stampCreateForm.jsp
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>


<!-- form start -->
<s:form beanclass="cz.muni.fi.pa165.bottler.web.StampsActionBean" id="stampCreateForm">
    <s:hidden name="modal_form" value="true" />

    <div class="modal modal_form" id="createStampModal" tabindex="-1" role="dialog" aria-labelledby="createStampModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><f:message key="stamp.create"/></h4>
                </div>

                <div class="modal-body">

                    <s:errors/>

                    <%@include file="stampForm.jsp"%>

                </div>
                <div class="modal-footer">

                    <button type="button" class="btn btn-default" data-dismiss="modal"><f:message key="cancel"/></button>

                    <s:submit name="create" class="btn btn-primary"><f:message key="stamp.create"/></s:submit>
                    </div>




                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->


</s:form>


bottler-web/src/main/webapp/blocks/stampForm.jsp
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib prefix="f" uri="http://java.sun.com/jsp/jstl/fmt" %>


<div class="form-group">
    <label for="stamp_bottle_input"><f:message key="stamp.number_of_stamp"/></label>

    <s:text name="stamp.numberOfStamp" class="form-control" id="stamp_bottle_input" />

</div>

<div class="form-group">
    <label for="stamp_time_input"><f:message key="stamp.issued_date"/></label>

    <div class='input-group date' id='datetimepicker1'>
        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
        </span>

        <%-- !! HACK !! - <s:text> doesn't accept data-format parameter --%>
        <input data-format="YYYY-MM-DD HH:mm:ss" type="text" class="hidden"></input>

        <s:text name="stamp.issuedDate" class="form-control"
                id="stamp_time_input"/>
    </div>

</div>

<script type="text/javascript">
    $(function() {
        $('#datetimepicker1').datetimepicker({
        });
        var dateInput = $('#datetimepicker1 input.form-control');
        var dateString = dateInput.val();
        dateString = dateString.replace('T', ' ').substr(0, 19);
        dateInput.val(dateString);
    });
</script>

<!-- <button type="submit" class="btn btn-default">Create stamp</button>-->

bottler-web/src/main/webapp/blocks/stampList.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="f" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<s:useActionBean beanclass="cz.muni.fi.pa165.bottler.web.StampsActionBean" var="actionBean"/>
<script>
    $(document).ready(function() {

        // apply the table sorter
        $("#stampsList").tablesorter({
            theme: "bootstrap",
            // disable sorting on buttons
            headers: {2: {sorter: false}},
            widthFixed: true,
            headerTemplate: '{content} {icon}', // new in v2.7. Needed to add the bootstrap icon!

            // widget code contained in the jquery.tablesorter.widgets.js file
            // use the zebra stripe widget if you plan on hiding any rows (filter widget)
            widgets: ["uitheme", "filter", "zebra"],
            widgetOptions: {
                // using the default zebra striping class name, so it actually isn't included in the theme variable above
                // this is ONLY needed for bootstrap theming if you are using the filter widget, because rows are hidden
                zebra: ["even", "odd"],
                // reset filters button
                filter_reset: ".reset"
            }
        });


    });
</script>
<table class="table table-hover" id="stampsList">
    <thead>
        <tr>
            <th><f:message key="stamp.number_of_stamp"/></th>
            <th><f:message key="stamp.issued_date"/></th>
            <c:if test="${actionBean.userIsPermittedToEdit || actionBean.userIsPermittedToDelete}">
                <th class="filter-false" style="width:160px">&nbsp;</th>
            </c:if>
        </tr>
    </thead>
    <tbody>
        <c:forEach items="${actionBean.tests}" var="stamp">
            <tr class="with-button row-link">
                <td>
                    <s:link beanclass="cz.muni.fi.pa165.bottler.web.StampsActionBean" event="detail">
                        <s:param name="stamp.id" value="${stamp.id}"/><c:out value="${stamp.numberOfStamp}"/>
                    </s:link>
                </td>
                <td>
                    <time class="timeago" datetime="<c:out value="${stamp.issuedDate}"/>">
                        <c:out value="${stamp.issuedDate}"/>
                    </time>
                </td>

                <c:if test="${actionBean.userIsPermittedToEdit || actionBean.userIsPermittedToDelete}">

                <td style="width:150px;text-align:right" class="no-link">
                   <!-- <button type="button" class="btn btn-default btn-sm" onclick="stampEdit(${stamp.id});">
                        <span class="glyphicon glyphicon-edit"></span> Edit
                    </button>-->

                    <s:form beanclass="cz.muni.fi.pa165.bottler.web.StampsActionBean">

                        <c:if test="${actionBean.userIsPermittedToEdit }">
                            <s:link class="btn btn-primary btn-sm" beanclass="cz.muni.fi.pa165.bottler.web.StampsActionBean" event="edit">
                                <s:param name="stamp.id" value="${stamp.id}"/><f:message key="edit"/>
                            </s:link>
                        </c:if>


                        <s:hidden name="stamp.id" value="${stamp.id}"/>

                        <f:message key="areyousuretodelete" var="msg">
                <f:param value="${stamp.numberOfStamp}" />
            </f:message>

            <s:submit class="btn btn-danger btn-sm" onclick="return confirm('${msg}');" name="delete"> <f:message key="delete"/></s:submit>


        </s:form>



    </td>
    </c:if>
</tr>

</c:forEach>

</tbody>



</table>
<c:if test="${fn:length(actionBean.tests) == 0}">
    <div class="alert alert-warning"> <f:message key="noitemsfound" /></div>
</c:if>

bottler-web/src/main/webapp/blocks/storeBottlesList.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="f" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="joda" uri="http://www.joda.org/joda/time/tags" %>

<s:useActionBean beanclass="cz.muni.fi.pa165.bottler.web.StoresActionBean" var="storesActionBean"/>
<script>
    $(document).ready(function() {
        // apply the table sorter
        $("#bottlesList").tablesorter({
            theme: "bootstrap",
            // disable sorting on buttons
            headers: {6: {sorter: false}},
            widthFixed: true,
            headerTemplate: '{content} {icon}', // new in v2.7. Needed to add the bootstrap icon!
            // widget code contained in the jquery.tablesorter.widgets.js file
            // use the zebra stripe widget if you plan on hiding any rows (filter widget)
            widgets: ["uitheme", "filter", "zebra"],
            widgetOptions: {
                // using the default zebra striping class name, so it actually isn't included in the theme variable above
                // this is ONLY needed for bootstrap theming if you are using the filter widget, because rows are hidden
                zebra: ["even", "odd"],
                // reset filters button
                filter_reset: ".reset"
            }
        });
    });
</script>

<table class="table table-hover" id="bottlesList">
    <thead>
        <tr>
            <th style="width:50px">ID</th>
            <th><f:message key="bottle.liquor"/></th>
            <th><f:message key="bottle.stamp"/></th>
            <th><f:message key="bottle.producedDate"/></th>
            <th><f:message key="bottle.lotCode"/></th>

        </tr>
    </thead>

    <tbody>
        <c:forEach items="${storesActionBean.bottles}" var="bottle">
            <tr class="with-button row-link">
                <td>
                    <s:link beanclass="cz.muni.fi.pa165.bottler.web.BottlesActionBean" event="detail">
                        <s:param name="bottle.id" value="${bottle.id}"/><c:out value="${bottle.id}"/>
                    </s:link>
                </td>

                <td>
                    <s:link beanclass="cz.muni.fi.pa165.bottler.web.BottlesActionBean" event="detail">
                        <s:param name="bottle.id" value="${bottle.id}"/><c:out value="${bottle.liquor.name}"/>
                    </s:link>
                </td>
                <td><c:out value="${bottle.stamp.numberOfStamp}"/></td>


                <td>
                    <joda:format value="${bottle.producedDate}" pattern="yyyy-MM-dd HH:mm:ss" />

                </td>


                <td><c:out value="${bottle.lotCode}"/></td>


            </tr>
        </c:forEach>
    </tbody>
</table>

<c:if test="${fn:length(storesActionBean.bottles) == 0}">
    <div class="alert alert-warning"> <f:message key="noitemsfound" /></div>

</c:if>

bottler-web/src/main/webapp/blocks/storeCreateForm.jsp
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>


<!-- form start -->
<s:form beanclass="cz.muni.fi.pa165.bottler.web.StoresActionBean" id="storeCreateForm">
    
    <s:hidden name="modal_form" value="true" />
    <div class="modal modal_form" id="createStoreModal" tabindex="-1" role="dialog" aria-labelledby="createStoreModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><f:message key="store.create"/></h4>
                </div>

                <div class="modal-body">

                    <s:errors/>

                    <%@include file="storeForm.jsp"%>

                </div>
                <div class="modal-footer">

                    <button type="button" class="btn btn-default" data-dismiss="modal"><f:message key="cancel"/></button>

                    <s:submit name="create" class="btn btn-primary"><f:message key="store.create"/></s:submit>
                    </div>




                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->


</s:form>


bottler-web/src/main/webapp/blocks/storeSearchForm.jsp
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>


<!-- form start -->
<s:form  class="form-horizontal" beanclass="cz.muni.fi.pa165.bottler.web.StoresActionBean">


    <div class="form-group">
        <label for="store_address_input" class="col-sm-2 control-label"><f:message key="store.address"/></label>
        <div class="col-sm-5">
            <s:text name="store.address" class="form-control" id="store_address_input" />
        </div>
        <div class="col-sm-3">
            <s:submit name="search" class="btn btn-primary"><f:message key="search.search"/></s:submit>
        </div>
    </div>







</s:form>

bottler-web/src/main/webapp/blocks/testResultForm.jsp
<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib prefix="f" uri="http://java.sun.com/jsp/jstl/fmt" %>


<s:useActionBean beanclass="cz.muni.fi.pa165.bottler.web.TestResultsActionBean" var="testResultsActionBean"/>
<div class="form-group">
    <label for="testresult_bottle_input"><f:message key="testresult.bottle"/></label>

    <s:select name="testResult.bottle" class="form-control" id="testresult_bottle_input">
        <s:options-collection collection="${testResultsActionBean.bottles}"
                              label="liquor.name" value="id"/>
    </s:select>
</div>

<div class="form-group">
    <label for="testresult_time_input"><f:message key="testresult.time"/></label>

    <div class='input-group date' id='datetimepicker1'>
        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
        </span>

        <%-- !! HACK !! - <s:text> doesn't accept data-format parameter --%>
        <input data-format="YYYY-MM-DD HH:mm:ss" type="text" class="hidden"></input>

        <s:text name="testResult.time" class="form-control" id="testresult_time_input" />

    </div>
</div>

<div class="form-group">
    <label for="testresult_toxic_input"><f:message key="testresult.toxic"/></label>
    <s:checkbox name="testResult.toxic" class="form-control" id="testresult_toxic_input" />
</div>

<script type="text/javascript">
    $(function() {
        $('#datetimepicker1').datetimepicker({
        });
        var dateInput = $('#datetimepicker1 input.form-control');
        var dateString = dateInput.val();
        dateString = dateString.replace('T', ' ').substr(0, 19);
        dateInput.val(dateString);
    });
</script>

<!-- <button type="submit" class="btn btn-default">Create testresult</button>-->